### PR TITLE
Exercise 1 Justus

### PR DESCRIPTION
**Pull request by Saiki77**

### CODE REVIEW

**Review by PixelWelt — APPROVED** [review]

**Review by atrejut — COMMENTED** [review]
please exclude the `.DS_Store`-files from the PR. Generally it's a good idea to add files to a PR explicitly (`git add <filename>`). Using `git add -A` is very much discouraged.

**Comment by atrejut** [comment]
@Saiki77 please remove the .DS_Store files as mentioned above and work towards getting the PR merged. Let me know if you need help removing those extra files.

**Review by atrejut — CHANGES_REQUESTED** [review]
Just noticed: You're also modifying the template file. Please make a copy in your own subfolder instead.

**Comment by Saiki77** [comment]
> Just noticed: You're also modifying the template file. Please make a copy in your own subfolder instead.

I removed the .DS-Store files, added a new folder and restored the Exercise file. I also added the .DS_Store file to the git ignore file, is this ok? @atrejut

**Comment by atrejut** [comment]
@Saiki77 adding `.DS_Store` to gitignore is absolutely ok -- but it was already added by another PR, and is in the current `.gitignore` in main (at the very bottom). You should probably not add it a second time :)

**Review by atrejut — APPROVED** [review]
thanks for fixing the file structure

**Pull request merged**
